at/Presentation/Models/DeveloperViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Presentation.Models
{
    public class DeveloperViewModel
    {
        public Guid Id { get; set; }
        [Required]
        [StringLength(150, MinimumLength = 5)]
        [Display(Name = "Nome")]
        public string FirstName { get; set; }
        [Required]
        [StringLength(150)]
        [Display(Name = "Sobrenome")]
        public string LastName { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Data de formação")]
        public DateTime GraduationDate { get; set; }
        [Display(Name = "Empregado")]
        public bool EmployedStatus { get; set; }
        [Range(minimum:0, maximum:999)]
        [Display(Name = "Apps publicados")]
        public int? PublishedApps { get; set; }

        public string FullName => $"{FirstName} {LastName}";

        public List<MobileAppViewModel> MobileApps { get; set; }
    }
}

at/Presentation/Controllers/DeveloperController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Presentation.Models;
using Presentation.Services;

namespace Presentation.Controllers
{
    [Authorize]
    public class DeveloperController : Controller
    {
        private readonly IDeveloperHttpService _developerHttpService;

        public DeveloperController(
            IDeveloperHttpService developerHttpService)
        {
            _developerHttpService = developerHttpService;
        }

        // GET: Developer
        public async Task<IActionResult> Index(DeveloperIndexViewModel developerIndexRequest)
        {
            var developerIndexViewModel = new DeveloperIndexViewModel
            {
                Search = developerIndexRequest.Search,
                OrderAscendant = developerIndexRequest.OrderAscendant,
                Developers = await _developerHttpService.GetAllAsync(
                    developerIndexRequest.OrderAscendant,
                    developerIndexRequest.Search)
            };
            return View(developerIndexViewModel);
        }

        // GET: Developer/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var developerViewModel = await _developerHttpService.GetByIdAsync(id.Value);

            if (developerViewModel == null)
            {
                return NotFound();
            }

            return View(developerViewModel);
        }

        // GET: Developer/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Developer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DeveloperViewModel developerViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(developerViewModel);
            }
            
            var developerCreated = await _developerHttpService.CreateAsync(developerViewModel);

            return RedirectToAction(nameof(Details), new {id = developerCreated.Id});
        }

        // GET: Developer/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var developerViewModel = await _developerHttpService.GetByIdAsync(id.Value);

            if (developerViewModel == null)
            {
                return NotFound();
            }

            return View(developerViewModel);
        }

        // POST: Developer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, DeveloperViewModel developerViewModel)
        {
            if (id != developerViewModel.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(developerViewModel);
            }
            
            try
            {
                await _developerHttpService.EditAsync(developerViewModel);
            }
            catch (DbUpdateConcurrencyException)
            {
                var exists = await developerViewModelExistsAsync(developerViewModel.Id);

                if (!exists)
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Developer/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var developerViewModel = await _developerHttpService.GetByIdAsync(id.Value);

            if (developerViewModel == null)
            {
                return NotFound();
            }

            return View(developerViewModel);
        }

        // POST: Developer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _developerHttpService.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> developerViewModelExistsAsync(Guid id)
        {
            var developer = await _developerHttpService.GetByIdAsync(id);

            var any = developer != null;

            return any;
        }
    }
}

at/Presentation/Controllers/MobileAppController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Presentation.Models;
using Presentation.Services;

namespace Presentation.Controllers
{
    [Authorize]
    public class MobileAppController : Controller
    {
        private readonly IMobileAppHttpService _mobileAppHttpService;
        private readonly IDeveloperHttpService _developerHttpService;

        public MobileAppController(
            IMobileAppHttpService mobileAppHttpService,
            IDeveloperHttpService developerHttpService)
        {
            _mobileAppHttpService = mobileAppHttpService;
            _developerHttpService = developerHttpService;

        }

        // GET: Developer
        public async Task<IActionResult> Index(MobileAppIndexViewModel mobileAppIndexRequest)
        {
            var mobileAppIndexViewModel = new MobileAppIndexViewModel
            {
                Search = mobileAppIndexRequest.Search,
                OrderAscendant = mobileAppIndexRequest.OrderAscendant,
                MobileApps = await _mobileAppHttpService.GetAllAsync(
                    mobileAppIndexRequest.OrderAscendant,
                    mobileAppIndexRequest.Search)
            };
           
            return View(mobileAppIndexViewModel);
        }

        // GET: Developer/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mobileAppViewModel = await _mobileAppHttpService.GetByIdAsync(id.Value);

            if (mobileAppViewModel == null)
            {
                return NotFound();
            }

            return View(mobileAppViewModel);
        }

        // GET: Developer/Create
        public async Task<IActionResult> Create()
        {
            await FillWithSelectedDevelopers();

            return View();
        }

        // POST: Developer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MobileAppViewModel mobileAppViewModel)
        {
            if (!ModelState.IsValid)
            {
                await FillWithSelectedDevelopers(mobileAppViewModel.DeveloperId);

                return View(mobileAppViewModel);
            }

            var mobileAppCreated = await _mobileAppHttpService.CreateAsync(mobileAppViewModel);

            return RedirectToAction(nameof(Details), new { id = mobileAppCreated.Id });
        }

        private async Task FillWithSelectedDevelopers(Guid? developerId = null)
        {
            var developers = await _developerHttpService.GetAllAsync(true);

            ViewBag.Developers = new SelectList(
                developers,
                nameof(DeveloperViewModel.Id),
                nameof(DeveloperViewModel.FullName),
                developerId);
        }

        // GET: Developer/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mobileAppViewModel = await _mobileAppHttpService.GetByIdAsync(id.Value);

            if (mobileAppViewModel == null)
            {
                return NotFound();
            }

            await FillWithSelectedDevelopers(mobileAppViewModel.DeveloperId);

            return View(mobileAppViewModel);
        }

        // POST: Developer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, MobileAppViewModel mobileAppViewModel)
        {
            if (id != mobileAppViewModel.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                await FillWithSelectedDevelopers(mobileAppViewModel.DeveloperId);

                return View(mobileAppViewModel);
            }
            try
            {
                await _mobileAppHttpService.EditAsync(mobileAppViewModel);
            }
            catch (DbUpdateConcurrencyException)
            {
                var exists = await MobileAppViewModelExistsAsync(mobileAppViewModel.Id);

                if (!exists)
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Developer/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mobileAppViewModel = await _mobileAppHttpService.GetByIdAsync(id.Value);

            if (mobileAppViewModel == null)
            {
                return NotFound();
            }
            return View(mobileAppViewModel);
        }

        // POST: Developer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _mobileAppHttpService.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
 
        private async Task<bool> MobileAppViewModelExistsAsync(Guid id)
        {
            var developer = await _mobileAppHttpService.GetByIdAsync(id);

            var any = developer != null;

            return any;
        }

        [AcceptVerbs("GET", "POST")]
        public async Task<IActionResult> IsUnusedName(string appName, Guid id)
        {
            return await _mobileAppHttpService.IsUnusedNameAsync(appName, id) 
                ? Json(true) 
                : Json($"O nome {appName} já está sendo usado.");
        }
    }
}

at/Presentation/Views/Developer/Create.cshtml
@model DeveloperViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Developers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GraduationDate" class="control-label"></label>
                <input asp-for="GraduationDate" class="form-control" />
                <span asp-validation-for="GraduationDate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="EmployedStatus" /> @Html.DisplayNameFor(model => model.EmployedStatus)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

at/Presentation/Views/Developer/Delete.cshtml
@model DeveloperViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Developers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GraduationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GraduationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployedStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployedStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishedApps)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishedApps)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

at/Presentation/Views/Developer/Details.cshtml
@using System.Linq
@model DeveloperViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Developers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GraduationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GraduationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployedStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployedStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishedApps)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishedApps)
        </dd>
    </dl>
    
    <table class="table">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MobileApps.First().AppName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MobileApps.First().PublishedStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MobileApps.First().PublishedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MobileApps.First().ModificationDate)
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.MobileApps) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AppName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublishedStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublishedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModificationDate)
                </td>
                <td>
                    <a asp-controller="MobileApp" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="MobileApp" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-controller="MobileApp" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
        </tbody>
    </table>

</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

at/Presentation/Views/Developer/Edit.cshtml
@model DeveloperViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Developers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GraduationDate" class="control-label"></label>
                <input asp-for="GraduationDate" class="form-control" />
                <span asp-validation-for="GraduationDate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="EmployedStatus" /> @Html.DisplayNameFor(model => model.EmployedStatus)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

at/Presentation/Views/Developer/Index.cshtml
@using System.Linq
@model DeveloperIndexViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Search</h1>
<form asp-action="Index">
    <label>Busca:</label>
    <input type="text" asp-for="@Model.Search" />
    <br />
    <label>Ordenação por Nome:</label>
    <select asp-for="OrderAscendant">
        <option value="@true">Ascendente</option>
        <option value="@false">Descendente</option>
    </select>
    <br />
    <button>go!</button>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>

@{
    if (Model.Developers == null || !Model.Developers.Any())
    {
        <p>Nenhum Desenvolvedor cadastrado :(</p>
        return;
    }
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Developers.First().FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Developers.First().LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Developers.First().GraduationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Developers.First().EmployedStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Developers.First().PublishedApps)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Developers)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GraduationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmployedStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublishedApps)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>